// posit.h

// ==================== NOTE: POTENTIAL HARDWARE HAZARD =======================
// `pmv.x.w` instruction potentially has latency that is not properly resolved
// at hardware level. This makes optimized code generated by LLVM vulernable.
//
// LLVM controls when to move value from PosReg to GPR with `pmv.x.w`, and in
// certain scenarios, subsequent operations using the GPR may not receive the
// correctly copied value.
//
// The workaround is to manually call `pmvxw` in cases where we know PosReg has
// to be moved to GPR, such as comparing a Pos number with an immediate value
// (which lives in GPR). This prevents LLVM from defering the `pmv.x.w` insn to
// a potentially hazardous location.
//
// Note that nesting `pmvxw` call is safe and efficient, as LLVM optimizes away
// redundant `pmvxw` call if the value is already in GPR.
//
// The `pmvxw` call is NOT built into any arithmetic operations in the lib, in
// order to allow LLVM to optimize register allocation by keeping Pos numbers
// inside PosReg, and reduce number of reg-to-reg copies during Pos arithmetic.
//
// The hardware hazard theory is only a hypothesis and is not confirmed. There
// may be a bug in llvm-xposit that caused this issue, but the author cannot
// discover such an issue. Also, note that `pmv.w.x` is likely not vulnerable.
// ============================================================================

#ifndef POSIT_H
#define POSIT_H

#include <stdint.h>
#include <stdbool.h>

// allow custom config for posit bits
// default: 32 bits
#ifndef POSIT_BITS
#define POSIT_BITS 32
#endif

#if POSIT_BITS == 8
#define UINT_TYPE uint8_t
#define INT_TYPE int8_t
#else
#if POSIT_BITS == 16
#define UINT_TYPE uint16_t
#define INT_TYPE int16_t
#else
#if POSIT_BITS == 32
#define UINT_TYPE uint32_t
#define INT_TYPE int32_t
#else
#error "Invalid POSIT_BITS"
#endif
#endif
#endif

typedef INT_TYPE posit_t;

static inline posit_t padd(posit_t x, posit_t y) {
    posit_t result = 0;

    asm inline volatile (
        "padd.s %0,%1,%2   \n"

        : "=p" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline posit_t psub(posit_t x, posit_t y) {
    posit_t result = 0;

    asm inline volatile (
        "psub.s %0,%1,%2   \n"

        : "=p" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline posit_t pmul(posit_t x, posit_t y) {
    posit_t result = 0;

    asm inline volatile (
        "pmul.s %0,%1,%2   \n"

        : "=p" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline posit_t pdiv(posit_t x, posit_t y) {
    posit_t result = 0;

    asm inline volatile (
        "pdiv.s %0,%1,%2   \n"

        : "=p" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline posit_t psqrt(posit_t x) {
    posit_t result = 0;

    asm inline volatile (
        "psqrt.s %0,%1     \n"

        : "=p" (result)
        : "p" (x)
        :
    );

    return result;
}

static inline posit_t pmin(posit_t x, posit_t y) {
    posit_t result = 0;

    asm inline volatile (
        "pmin.s  %0,%1,%2  \n"

        : "=p" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline posit_t pmax(posit_t x, posit_t y) {
    posit_t result = 0;

    asm inline volatile (
        "pmax.s  %0,%1,%2  \n"

        : "=p" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline INT_TYPE pcvtws(posit_t x) {
    INT_TYPE result = 0;

    asm inline volatile (
        "pcvt.w.s %0,%1    \n"

        : "=r" (result)
        : "p" (x)
        :
    );

    return result;
}

static inline UINT_TYPE pcvtwus(posit_t x) {
    UINT_TYPE result = 0;

    asm inline volatile (
        "pcvt.wu.s %0,%1   \n"

        : "=r" (result)
        : "p" (x)
        :
    );

    return result;
}

static inline posit_t pcvtsw(INT_TYPE x) {
    posit_t result = 0;

    asm inline volatile (
        "pcvt.s.w %0,%1    \n"

        : "=p" (result)
        : "r" (x)
        :
    );

    return result;
}

static inline posit_t pcvtswu(UINT_TYPE x) {
    posit_t result = 0;

    asm inline volatile (
        "pcvt.s.wu %0,%1   \n"

        : "=p" (result)
        : "r" (x)
        :
    );

    return result;
}

static inline INT_TYPE pmvxw(posit_t x) {
    INT_TYPE result = 0;

    asm inline volatile (
        "pmv.x.w %0,%1     \n"

        : "=r" (result)
        : "p" (x)
        :
    );

    return result;
}

static inline posit_t pmvwx(INT_TYPE x) {
    posit_t result = 0;

    asm inline volatile (
        "pmv.w.x %0,%1     \n"

        : "=p" (result)
        : "r" (x)
        :
    );

    return result;
}

static inline bool peq(posit_t x, posit_t y) {
    bool result = 0;

    asm inline volatile (
        "peq.s  %0,%1,%2   \n"

        : "=r" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline bool plt(posit_t x, posit_t y) {
    bool result = 0;

    asm inline volatile (
        "plt.s  %0,%1,%2   \n"

        : "=r" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

static inline bool ple(posit_t x, posit_t y) {
    bool result = 0;

    asm inline volatile (
        "ple.s  %0,%1,%2   \n"

        : "=r" (result)
        : "p" (x), "p" (y)
        :
    );

    return result;
}

#endif
